random_seed: 42
dataset:
  version: "v1"  # can be v1, v2, v3
  split:
    train: 0.7
    val: 0.15
    test: 0.15

model:
  architecture: "cnn"
  learning_rate: 0.001
  batch_size: 64
  epochs: 30
  conv_layers: 3
  conv_filters: [32, 64, 128]
  kernel_sizes: [3, 3, 3]
  dropout_rate: 0.5
  
# Parameters for hyperparameter tuning
tuning:
  param1: "learning_rate"
  param1_values: [0.0001, 0.001, 0.01]
  param2: "dropout_rate"
  param2_values: [0.3, 0.5, 0.7]